### ISSUE TITLE
Make "Fix Issues" icon the Update icon if only issue is an update

### ISSUE THREAD

**Issue by GameWyrm** [ow-mods/ow-mod-man#182]
### Package

Graphical Interface

### Feature

The wrench and hammer icon makes it look like there is something actually wrong with the mod besides being out of date. I think it would be more intuitive for the user if that icon used the standard Update icon if the only issue is the need to update.

**Comment by Bwc9876** [comment]
Thought a lot about this, making the icon an update button would cause a discrepancy in a lot of the language used regarding updates. At its core, not updating your mod **is a validation error** internally, so it makes sense that it shows as an error. Arguably it's an error in this use case because an outdated mod can result in the game not loading etc. So yeah it makes it look like something's wrong with the mod because there is.
