### ISSUE TITLE
[Bug Report] Steam Deck - Mod Folder Not found

### ISSUE THREAD

**Issue by Annyastalya** [ow-mods/ow-mod-man#501]
### What Happened?

Hello! This is my first time using mods for Outer Wilds. I installed the mod manager, the mod loader and a few mods. When choosing to run the game, the mods won't load. The game log reads "Warning - Mod folder not found". 

I'm currently on steam deck. Downloaded the mod manager via the discover shop. At first the manager wouldn't find the game, so I manually wrote the game folder path since it's on external storage on a micro sd card. After that, it runs the game with no problem, but there won't be any mods loaded. 

![Screenshot_20240402_220452](https://github.com/ow-mods/ow-mod-man/assets/165839097/6289efbc-c403-40fe-9b3b-4b1b409142bb)
![Screenshot_20240402_220514](https://github.com/ow-mods/ow-mod-man/assets/165839097/147a14f5-dc78-41f5-80bb-3b855f33cc2f)

### Package

Graphical Interface

### Platform

Steam Deck

### Logs

[19-03-08.log](https://github.com/ow-mods/ow-mod-man/files/14843180/19-03-08.log)

**Comment by Shiver-J** [comment]
I am having the same issue on my desktop running Fedora 40 (though it also happened on 39). I have the Steam package from Flathub and the game installed on a secondary hard drive. It launches with the manager just fine but fails to detect and load the mods themselves.

**Comment by Bwc9876** [comment]
Hi there! The Flatpak version of the mod manager only has access to the default install directory of the game. Also, the "Browse" button is sadly broken on Flatpak as it tried to make a portal to the game instead of just inserting the path. I'd recommend moving the game to the default Steam library location and clicking the "Reset" button on the OWML settings sections to get the default path back.

**Comment by Shiver-J** [comment]
This solution did not work for me, as I have the Flatpak version of Steam, so games are installed on a different directory than the one the mod manager labels as the default, leaving me unable to use it.

**Comment by Bwc9876** [comment]
Okay then I'll add the flatpak version of steam's share folder to the allowed FS paths (`~/.var/app/com.valvesoftware.Steam/.local/share/OuterWildsModManager`) it's goiing to take a while for the update to go through but after that you should be able to set the OWML path to that, re-verify the game's integrity, and try launching with mods again.

**Comment by Bwc9876** [comment]
Okay the release has been published on flathub, it may take a bit for it fully go through so I'd wait an hour but after that you can try the steps above

**Comment by Shiver-J** [comment]
I haven't received the update yet. I looked into the flathub repo and it looks like it was rejected by the moderation team. Not sure as to why though.
https://github.com/flathub/com.outerwildsmods.owmods_gui/issues/60

**Comment by Bwc9876** [comment]
Update should be live now

**Comment by Shiver-J** [comment]
Still haven’t received it. I checked on both my software manager and the flathub site itself and it either hasn't been approved yet or something went wrong with the request.

**Comment by Shiver-J** [comment]
I got the update! At first it gave me the same issues, and when I went to select the new path for the mod loader it turned out the directory hadn't been created, so I had to manually copy and paste the OuterWildsModManager/OWML folders directly to the steam .local/share directory, but once I did that it loaded up the mods! I'm not sure if that was exactly how it was supposed to go, but it worked, so regardless, thanks for helping me out on this, I appreciate it a ton :)
